import { Category, Post } from "./interfaces";

export const categories: Category[] = [
  {
    id: 1,
    documentId: "cat_react",
    name: "React",
    slug: "react",
    color: "#61DAFB",
    description:
      "Biblioteca de JavaScript para construir interfaces de usuario basadas en componentes reutilizables y una gestión eficiente del estado mediante el Virtual DOM.",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    publishedAt: new Date("2024-01-01"),
    posts: [],
    cover_image: "",
  },
  {
    id: 2,
    documentId: "cat_css",
    name: "CSS",
    slug: "css",
    color: "#1572B6",
    description:
      "Lenguaje de diseño encargado de definir la presentación visual, el diseño y el estilo de los documentos estructurados en HTML.",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    publishedAt: new Date("2024-01-01"),
    posts: [],
    cover_image: "",
  },
  {
    id: 3,
    documentId: "cat_javascript",
    name: "Javascript",
    slug: "javascript",
    color: "#f7df1e",
    description:
      "Lenguaje de programación de alto nivel, interpretado y orientado a objetos, fundamental para crear interactividad en páginas web.",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    publishedAt: new Date("2024-01-01"),
    posts: [],
    cover_image: "",
  },
  {
    id: 4,
    documentId: "cat_nodejs",
    name: "NodeJs",
    slug: "node-js",
    color: "#8dc94a",
    description:
      "Entorno de ejecución de JavaScript construido con el motor V8 de Chrome que permite ejecutar código del lado del servidor.",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    publishedAt: new Date("2024-01-01"),
    posts: [],
    cover_image: "",
  },
  {
    id: 5,
    documentId: "cat_python",
    name: "Python",
    slug: "python",
    color: "#2371b1",
    description:
      "Lenguaje de programación versátil y de sintaxis clara, ampliamente utilizado en ciencia de datos, inteligencia artificial y desarrollo backend.",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    publishedAt: new Date("2024-01-01"),
    posts: [],
    cover_image: "",
  },
  {
    id: 6,
    documentId: "cat_typescript",
    name: "Typescript",
    slug: "typescript",
    color: "#3178c6",
    description:
      "Superconjunto de JavaScript que añade tipado estático opcional, facilitando el desarrollo de aplicaciones robustas y a gran escala.",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    publishedAt: new Date("2024-01-01"),
    posts: [],
    cover_image: "",
  },
];

export const posts: Post[] = [
  {
    id: 1,
    documentId: "post_001",
    title: "Introducción a React Hooks: useState y useEffect",
    slug: "introduccion-react-hooks-usestate-useeffect",
    excerpt:
      "Aprende los fundamentos de los hooks más utilizados en React y cómo pueden simplificar tu código",
    category: categories[0],
    views: 1523,
    read_time: 8,
    featured: true,
    createdAt: "2024-02-15T10:00:00.000Z",
    updatedAt: "2024-02-15T10:00:00.000Z",
    publishedAt: "2024-02-15T10:00:00.000Z",
    cover_image: "",
    seo: null,
    content: "",
  },
  {
    id: 2,
    documentId: "post_002",
    title: "CSS Grid vs Flexbox: ¿Cuándo usar cada uno?",
    slug: "css-grid-vs-flexbox",
    excerpt:
      "Descubre las diferencias clave entre Grid y Flexbox y aprende a elegir la herramienta correcta para cada situación",
    category: categories[1],
    views: 2156,
    read_time: 10,
    featured: false,
    createdAt: "2024-02-16T10:00:00.000Z",
    updatedAt: "2024-02-16T10:00:00.000Z",
    publishedAt: "2024-02-16T10:00:00.000Z",
    cover_image: "",
    seo: null,
    content: "",
  },
  {
    id: 3,
    documentId: "post_003",
    title: "TypeScript Generics: Guía completa para principiantes",
    slug: "typescript-generics-guia-completa",
    excerpt:
      "Domina los genéricos en TypeScript y escribe código más reutilizable y type-safe",
    category: categories[5],
    views: 1847,
    read_time: 12,
    featured: false,
    createdAt: "2024-02-17T10:00:00.000Z",
    updatedAt: "2024-02-17T10:00:00.000Z",
    publishedAt: "2024-02-17T10:00:00.000Z",
    cover_image: "",
    seo: null,
    content: "",
  },
  {
    id: 4,
    documentId: "post_004",
    title: "Node.js y Express: Construye tu primera API REST",
    slug: "nodejs-express-primera-api-rest",
    excerpt:
      "Aprende a crear una API RESTful completa con Node.js, Express y mejores prácticas",
    category: categories[3],
    views: 3421,
    read_time: 15,
    featured: true,
    createdAt: "2024-02-18T10:00:00.000Z",
    updatedAt: "2024-02-18T10:00:00.000Z",
    publishedAt: "2024-02-18T10:00:00.000Z",
    cover_image: "",
    seo: null,
    content: "",
  },
  {
    id: 5,
    documentId: "post_005",
    title: "Python: Decoradores explicados con ejemplos prácticos",
    slug: "python-decoradores-ejemplos-practicos",
    excerpt:
      "Entiende qué son los decoradores en Python y cómo pueden hacer tu código más limpio y reutilizable",
    category: categories[4],
    views: 1923,
    read_time: 11,
    featured: false,
    createdAt: "2024-02-19T10:00:00.000Z",
    updatedAt: "2024-02-19T10:00:00.000Z",
    publishedAt: "2024-02-19T10:00:00.000Z",
    cover_image: "",
    seo: null,
    content: "",
  },
];
